name: Deploy Backend Ktor to EC2

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Construir el Fat JAR (Igual que cuando haces doble clic en IntelliJ)
      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Create SSH Key File
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2 via SSH
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem build/libs/backend-all.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/backend.jar
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} "sudo systemctl restart adapp && sudo systemctl status adapp"